---
kvm_packages1: 
  - qemu
  - libvirt
  - libvirt-devel
  - ruby-devel
  - gcc
  - qemu-kvm
  - qemu-img
  - libvirt-python
  - libvirt-client
  - virt-install
  - virt-viewer
  - virt-manager
  - bridge-utils

kvm_packages2: 
  - 'http://linuxsoft.cern.ch/centos/8.1.1911/isos/x86_64/CentOS-8.1.1911-x86_64-dvd1.iso'

