---
- name: Download and unarchive terraform
  unarchive:
      src: https://releases.hashicorp.com/terraform/{{terraform_version}}/terraform_{{terraform_version}}_linux_amd64.zip
      dest: /usr/local
      remote_src: yes

- name: Create link to terraform
  file:
      src: /usr/local/terraform
      dest: /usr/local/bin/terraform
      state: link
  ignore_errors: true
