---
- name: Download and unarchive terraform
  unarchive:
      src: https://releases.hashicorp.com/terraform/{{terraform_version}}/terraform_{{terraform_version}}_linux_amd64.zip
      dest: /usr/local
      remote_src: yes

- name: Create link to terraform
  file:
      src: /usr/local/terraform
      dest: /usr/local/bin/terraform
      state: link
  ignore_errors: true

- name: Create folder for Terraform plugins
  become: no
  file:
      path: /home/{{current_user}}/.terraform.d/plugins
      state: directory
      mode: 0755
      owner: "{{ current_user }}"

- name: Download and unarchive terraform-provider-libvirt
  unarchive:
      src: https://github.com/dmacvicar/terraform-provider-libvirt/releases/download/{{ terraform_libvirt_version }}.tar.gz
      dest: /home/{{current_user}}/.terraform.d/plugins 
      remote_src: yes

- name: Create folder for Terraform project
  become: no
  file:
      path: /home/{{current_user}}/terraform_projects
      state: directory
      mode: 0755
      owner: "{{ current_user }}"
