---
- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: true
  become_method: su
  become_user: root
  roles: 
    - role: firstsetup
      vars: 
        host_name: kvmmain
        current_user: kvm-main
    
- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: true
  vars:
     - current_user: kvm-main
  roles:
    - kvm
    - role: packer
      vars:
        packer_version: 1.5.4
    - role: terraform
      vars:
        terraform_version: 0.12.23
    - role: python3
      vars:
        compiled_python_version: 3.8.2
    - pip
    - role: mynetwork
      vars:
        network_addr: 192.168.1.1/24
        bridge_device_name: 'virbr0'
    - nvidia 
##    - role: linux_desktop
##      vars:
##        linux_desktop: xfce
#    - nmclinetwork
       

  tasks:

  - name: debuging packer
    shell: /usr/local/packer --version
    register: packer_info

  - name: packer-info
    debug:
      msg: "{{ packer_info.stdout }}"

  - name: debuging terraform
    shell: /usr/local/terraform --version
    register: terraform_info

  - name: terraform-info
    debug:
      msg: "{{ terraform_info.stdout }}"

  - name: debuging python3 #check above the python3 version
    shell: python3.8 --version  
    register: python3_info

  - name: python3-info
    debug:
      msg: "{{ python3_info.stdout }}"

  - name: debuging pip3
    shell: pip3.7 --version
    register: pip3_info

  - name: pip3-info
    debug:
      msg: "{{ pip3_info.stdout }}"

  - debug:
      msg: "{{ static_ip_addr }}"

  - name: reloading GRUB to install nvidia driver 
    shell: grub2-mkconfig -o /boot/grub2/grub.cfg

  - debug:
      msg: "Reboot and run bash NVIDIA-Linux-x86_64-* in ~/Downloads"

