---
#- hosts: 127.0.0.1
#  connection: local
#  gather_facts: yes
#  become: true
#  become_method: su
#  become_user: root
#  roles: 
#    - firstsetup
##     vars: 
##        host_name: kvmmain
##        current_user: kvm-host
    
- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: true
  roles:
#    - nextstep
#    - packer
#    - terraform
#    - kvm
#    - nmclinetwork
##    - python3
##    - pip
    - role: mynetwork
      vars:
        network_addr: 192.168.1.1/24
##    - role: linux_desktop
##      vars:
##        linux_desktop: xfce
##    - kvm   

#  tasks:

#  - name: debuging packer
#    shell: /usr/local/packer --version
#    register: packer_info

#  - name: packer-info
#    debug:
#      msg: "{{ packer_info.stdout }}"

#  - name: debuging python3
#    shell: python3.7 --version  
#    register: python3_info

#  - name: python3-info
#    debug:
#      msg: "{{ python3_info.stdout }}"

#  - name: debuging pip3
#    shell: pip3.7 --version
#    register: pip3_info

#  - name: pip3-info
#    debug:
#      msg: "{{ pip3_info.stdout }}"

#  - debug:
#      msg: "{{ interface_device_name }}"

#  - debug:
#      msg: "{{ static_ip_addr }}"


